version: "3.8"
services:
  php73_18:
    image: "jiahaodong/php_fpm_7.3.18_temu:v4"
    ports:
      - "9000:9000"
      - "80:80"
    cap_add:
      - SYS_PTRACE
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./docker_common/log/php/:/var/log/php/"
      - "./docker_common/conf/php/php.ini:/usr/local/etc/php/php.ini"
      - "./docker_common/conf/php/php-fpm.conf:/usr/local/etc/php-fpm.conf"
      - "./docker_common/conf/php/php-fpm.d/:/usr/local/etc/php-fpm.d/"
      - "./docker_common/conf/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "./docker_common/conf/nginx/vhosts:/usr/local/openresty/nginx/conf/vhosts/"
      - "./docker_common/log/nginx/:/var/log/nginx/"
#      - "../../temu:/application/www/temu"
      - "../temu:/application/www/temu"
    working_dir: "/application/www"
#    networks:
#      - temu
    container_name: php73_18
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    #command: bash -c "service cron start && php-fpm -D && openresty && nohup chromedriver --port=4444 --allowed-ips=127.0.0.1 >/chromedriver.log 2>\\&1 \\& && echo 'php-fpm and openresty and cron and chromedriver start success !' && tail -f /dev/null"
    command: bash -c "service cron start && php-fpm -D && openresty && echo 'php-fpm and openresty and cron start success !' && tail -f /dev/null"
#networks:
#  temu:
#    #driver: bridge
#    external: true
